//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(DepartamentoMetadata))]
    public partial class DEPARTAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPARTAMENTO()
        {
            this.RESERVA = new HashSet<RESERVA>();
            this.EXTRA = new HashSet<EXTRA>();
        }
    
        public int Id { get; set; }
        
        public string Nombre { get; set; }
        
        public string Descripcion { get; set; }
        
        public int IdUbicacion { get; set; }
        
        public decimal Tarifa { get; set; }
        
        public bool Estado { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "La URL de la imagen es un campo obligatorio")]
        public string Imagen { get; set; }
    
      
        public virtual UBICACION UBICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA> RESERVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Incluye")]
        public virtual ICollection<EXTRA> EXTRA { get; set; }
    }
}
