//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVADETALLE
    {
        public int Id { get; set; }
        public Nullable<int> IdReserva { get; set; }
        public Nullable<int> IdTipoPago { get; set; }
        public string NumeroTarjeta { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> SubTotalServicio { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
        public virtual TIPOPAGO TIPOPAGO { get; set; }
    }
}
