//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SERVICIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIOS()
        {
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public int Id { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Nombre es un campo obligatorio")]
        [MinLength(6)]
        public string Nombre { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Descripción es un campo obligatorio")]
        [MinLength(6)]
        public string Descripcion { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Precio es un campo obligatorio")]
        public decimal Precio { get; set; }
        [Display(Name = "Disponibilidad")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La disponibilidad es una opción requerida")]
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
